{ lib, config, ... }:
let
  inherit (lib) types mkOption;
  inherit (lib.lists) optionals;
  inherit (lib.alchemy) isx86Linux;
  cfg = config.alchemy.boot;
  
  hasBtrfs = (lib.filterAttrs (_: v: v.fsType == "btrfs") config.fileSystems) != { };
  isX86 = config.nixpkgs.hostPlatform.system == "x86_64-linux";
in {
  options.alchemy.boot = {
    kernelModules = mkOption {
      type = types.listOf types.str;
      default = [];
    };
    availableKernelModules = mkOption {
      type = types.listOf types.str;
      default = [];
    };
  };
  
  config = {
    boot.initrd = {
      systemd.enable = (!config.boot.swraid.enable && !config.boot.isContainer);
      # Verbosity of the initrd
      # disabling verbosity removes only the mandatory messages generated by the NixOS
      verbose = false;
      
      kernelModules = [
        "nvme"
        "xhci_pci"
        "xhci_hcd"
        "ahci"
        "sd_mod"
        "dm_mod"
      ] ++ optionals hasBtrfs [
        "btrfs"
      ] ++ cfg.kernelModules;
        
      availableKernelModules = [
        "usbhid"
        "sd_mod"
        "sr_mod"
        "dm_mod"
        "uas"
        "usb_storage"
        "rtsx_usb_sdmmc"
        "rtsx_pci_sdmmc"
        "virtio_pci"
        "virtio_scsi"
        "virtio_blk"
        "ehci_pci"
      ] ++ optionals isX86 [
        "vmd"
        "ata_piix"
        "uhci_hcd"
      ] ++ cfg.availableKernelModules;
    };
  };
}
